name: 'Install dependencies'
description: 'Get code from repository and install composer dependencies'
runs:
  using: 'composite'
  steps:
    - uses: 'actions/checkout@v3'
    - name: 'Install composer'
      run: 'make composer'
      shell: 'bash'
