name: Install dependencies
description: Cache and install composer dependencies
runs:
  using: composite
  steps:
    - name: Cache composer dependencies
      uses: actions/cache@v3
      with:
        path: vendor
        key: deps-composer-${{ hashFiles('composer.lock') }}
    - name: Install dependencies
      run: make composer
      shell: bash
