version: '3.9'

services:
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
    volumes:
      - pg_data:/var/lib/postgresql/data:rw
    ports:
      - '15392:5432'

  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - database
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./:/srv/app

  nginx:
    image: nginx:1.25-alpine
    depends_on:
      - php
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public/:/srv/app/public
    ports:
      - '8050:80'

volumes:
  pg_data:
