name: Deploy
description: Deploy with SSH
inputs:
  ssh-host:
    description: 'SSH host'
    required: true
  ssh-port:
    description: 'SSH port'
    required: true
    default: '22'
  ssh-user:
    description: 'SSH user'
    required: true
  ssh-password:
    description: 'SSH password'
    required: true
runs:
  using: docker
  image: Dockerfile
