name: Deployment
on:
  push:
    branches:
      - main
      - feat-github-actions
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container: tunet/php-github-actions:0.1.0
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install
      - name: Run unit tests
        run: make run-unit-tests
  integration-tests:
    runs-on: ubuntu-latest
    container: tunet/php-github-actions:0.1.0
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install
      - name: Run integration tests
        run: make run-integration-tests
#  deploy:
#    runs-on: ubuntu-latest
#    needs: [unit-tests, integration-tests]
#    steps:
#      - uses: actions/checkout@v2
#      - name: Install dependencies
#        run: composer install
