name: Deploying
on:
  push:
    branches:
      - main
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container: tunet/php-github-actions:0.1.0
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Run unit tests
        run: make run-unit-tests
  integration-tests:
    services:
      database:
        image: postgres:13-alpine
        env:
          POSTGRES_DB: app_test
          POSTGRES_PASSWORD: app
          POSTGRES_USER: app
    runs-on: ubuntu-latest
    container: tunet/php-github-actions:0.1.0
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Run integration tests
        run: make run-integration-tests
  deploy:
    needs: [unit-tests, integration-tests]
    runs-on: ubuntu-latest
    container: tunet/php-github-actions:0.1.0
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Deploy
        run: echo "Deploying..."
