name: Deployment
on:
  push:
    branches:
      - main
      - feat-github-actions
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container: tunet/php-github-actions:0.1.0
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Run unit tests
        run: make run-unit-tests
  integration-tests:
    services:
      database:
        image: postgres:13-alpine
        env:
          POSTGRES_DB: app_test
          POSTGRES_PASSWORD: app
          POSTGRES_USER: app
    runs-on: ubuntu-latest
    container: tunet/php-github-actions:0.1.0
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Run integration tests
        run: make run-integration-tests
  deploy:
    runs-on: ubuntu-latest
    container: tunet/php-github-actions:0.1.0
    needs: [unit-tests, integration-tests]
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          ssh-host: ${{ secrets.SSH_HOST }}
          ssh-user: ${{ secrets.SSH_USER }}
          ssh-password: ${{ secrets.SSH_PASSWORD }}
