name: Deploying
on:
  push:
    branches:
      - main
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container: tunet/php-github-actions:0.1.0
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: make composer
      - name: Run unit tests
        run: make run-unit-tests
